BLOCKSDS ?= /opt/blocksds/core
WONDERFUL_TOOLCHAIN ?= /opt/wonderful

ARM_NONE_EABI_PATH := $(WONDERFUL_TOOLCHAIN)/toolchain/gcc-arm-none-eabi/bin
CC := $(ARM_NONE_EABI_PATH)/arm-none-eabi-gcc
AR := $(ARM_NONE_EABI_PATH)/arm-none-eabi-ar

BUILD_DIR ?= ../build/obj/core/blocksds
LIBRARY := $(BUILD_DIR)/libdualsync_core.a
SOURCES := $(wildcard source/*.c)
OBJECTS := $(patsubst source/%.c,$(BUILD_DIR)/%.o,$(SOURCES))

ARCH := -mthumb -mcpu=arm946e-s+nofp
SPECS := $(BLOCKSDS)/sys/crts/ds_arm9.specs
CFLAGS := -std=c11 -Wall -Wextra -Werror -Os \
	-ffunction-sections -fdata-sections \
	-Iinclude $(ARCH) -specs=$(SPECS)

.PHONY: all clean

all: $(LIBRARY)

$(LIBRARY): $(OBJECTS)
	@mkdir -p $(@D)
	$(AR) rcs $@ $^

$(BUILD_DIR)/%.o: source/%.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) -MMD -MP -c -o $@ $<

clean:
	rm -rf $(BUILD_DIR)

-include $(OBJECTS:.o=.d)
